Update jquery_warnings.adoc
owncloud/docs-server pull request #1129
Opened 2023-09-26 15:36 UTC by IljaN

2023-09-27 05:43 UTC, phil-davis approved these changes

2023-09-27 05:51 UTC, DeepDiver1975 commented
Can we please get proper commit message and PR title?

2023-09-27 05:51 UTC, DeepDiver1975 requested changes
See above

2023-09-27 07:46 UTC, DeepDiver1975 approved these changes

2023-10-02 07:50 UTC, mmattel approved these changes

2023-10-02 07:51 UTC, mmattel commented
This needs backporting to 10.13 and 10.12

2023-10-02 07:52 UTC, merged