Update generated volume name in index.adoc
owncloud/docs-server pull request #563
Opened 2022-08-06 10:33 UTC by msteiger

Having followed the instructions and using the provided `docker-compose.yml` file, the generated volume name is different from what is mentioned in the docs.

[modules/admin_manual/examples/installation/docker/docker-compose.yml](https://github.com/owncloud/docs-server/blob/master/modules/admin_manual/examples/installation/docker/docker-compose.yml)

My docker version is "Docker version 20.10.12, build 20.10.12-0ubuntu4" if that matters.

```bash
$ docker volume ls
DRIVER    VOLUME NAME
local     owncloud-setup_files
local     owncloud-setup_mysql
local     owncloud-setup_redis
```

2022-08-08 08:36 UTC, d7oc requested changes
The volume name depends on the `COMPOSE_PROJECT_NAME` which builds the first part of the volume and the name of the volume in the docker file. So it will differ by design as long as we don't set the `COMPOSE_PROJECT_NAME` in an `.env` file as the `COMPOSE_PROJECT_NAME` is build from the directory in which docker-compose is executed when not specified. That's by the way also the reason why you run into troubles when moving a docker-compose.yml file to another directory and try to execute it there. See https://docs.docker.com/compose/reference/envvars/#compose_project_name.
So the pattern for the volume will be < COMPOSE_PROJECT_NAME>_<VOLUME_NAME>. So we shouldn't modify the documentation like described in this patch, but I would vote for adding an `.env` file or the corresponding `-p` parameter to the `docker-compose` calls, so we fix the name.

2022-08-08 15:05 UTC, msteiger commented
Thank you for the clarification. I now understand how it works. In order to also help others, I summarized your explanation and put it in a short paragraph. It would be enough to clarify the naming pattern in the docs as a first step, imho. What do you think?

2022-08-08 17:45 UTC, mmattel commented on modules/admin_manual/pages/installation/docker/index.adoc
> +The naming pattern of the volume is `<COMPOSE_PROJECT_NAME>_<VOLUME_NAME>`.
```suggestion
The volume name depends on the project name which builds the first part of the volume and the name of the volume in the docker file. The naming pattern of the volume is `<COMPOSE_PROJECT_NAME>_<VOLUME_NAME>`. An environment variable for `COMPOSE_PROJECT_NAME` can be set and also be defined in a `.env` file. If not specified, the directory in which docker-compose is executed will be used as a name.
```

2022-08-08 17:46 UTC, mmattel commented
@d7oc I have made a review of the text.
Can you pls have a look if it is technically correct. Based on your ok I will proceed.

2022-08-09 07:34 UTC, d7oc submitted a review, later dismissed
I'm fine with that if the two suggestions are included. For a later stage we could also think about adding a standard `.env` file to the documentation or the `-p` parameter.

2022-08-09 07:34 UTC, d7oc commented on modules/admin_manual/pages/installation/docker/index.adoc
> +docker run -v owncloud-docker-server_files:/mnt \
Should be changed into the following as the name needs to found on each installation and is not fixed:

```suggestion
docker run -v <YOUR_DOCKER_VOLUME>:/mnt \
```

2022-08-09 07:34 UTC, d7oc commented on modules/admin_manual/pages/installation/docker/index.adoc
> +docker volume ls
We can leave a `grep` for `files` here as only the prefix will change, the name `files` is given in the compose file.

```suggestion
docker volume ls | grep files
```

2022-08-09 11:17 UTC, mmattel approved these changes

2022-08-09 11:18 UTC, mmattel commented
Backport to 10.10 and 10.9

2022-08-09 11:19 UTC, merged